# Generated by Django 2.2 on 2021-03-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_remove_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT74rffvV8qCFqMGpYxBYtmyIRzfku1op2r1A&usqp=CAU', max_length=6000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.TextField(default='https://blogs.biomedcentral.com/bmcblog/wp-content/uploads/sites/7/2015/07/adalovelace.jpg'),
        ),
    ]
